steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=trumpmeltdown-backend']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', 'main.go']
  env: ['PROJECT_ROOT=trumpmeltdown-backend']
artifacts:
  objects:
    location: 'gs://ajnhosting-binaries/trumpmeltdown'
    paths: ['trumpmeltdown-backend']
