steps:
- name: "gcr.io/cloud-builders/go"
  args: ["install", "github.com/ajn0592/trumpmeltdown-backend"]
  env: ["PROJECT_ROOT=github.com/ajn0592/trumpmeltdown-backend"]
artifacts:
  objects:
    location: 'gs://ajnhosting-binaries/trumpmeltdown'
    paths: ['trumpmeltdown-backend']
